[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
