[build]
builder = "nixpacks"
buildCommand = "rm -f package-lock.json && npm install --force && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
